apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlops-system
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://github.com/tuusuario/FINALMLOPS.git'
    targetRevision: HEAD
    path: k8s
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
